### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alwasega**
Update missing steps in the README file that are necessary to fetch, process, and analyze the Accra data.

### CODE REVIEW

**Comment by alwasega** [comment]
Tried to follow the steps in the present README file to test the utility to access the GridWatch Accra Dataset. 

However, ran into a number of problems, for instance, there is no mention of need to create Google Cloud credentials. This PR tries to make the instructions clearer for anyone interested in testing the nline-data-api utility.

**Comment by jacksongoode** [comment]
Hey Allan!

Thanks for checking this out! We actually realized this issue today as well. It seems like we need to specify the filesystem with a particular anon mode.

I've added this as a PR https://github.com/nline/nline-data-api/pull/2, maybe you can test it out when you have time? I think that would clear up many of the issues you've faced.

To sign out of `gcloud` you will need to run `gcloud auth revoke --all` and `gcloud auth application-default revoke` potentially as well.

**Comment by alwasega** [comment]
Hi Jackson!

Thanks for pushing the update. Yes, it resolves the issues I was facing, particularly with gcloud. 
However, one still needs to install `requests`, `pyarrow`, and `polars` (`polars-lts-cpu`, in my case). Is this the intended behavior? Apart from this, the fetching and analysis works with no issues.

**Comment by jacksongoode** [comment]
Hmm I think if you cd to the directory of the project, then call `uv sync` you should see something like:

```bash
❯ uv sync
Using Python 3.12.3
Creating virtualenv at: .venv
Resolved 47 packages in 6ms
Prepared 40 packages in 5ms
Installed 41 packages in 235ms
 + appnope==0.1.4
 + asttokens==2.4.1
 + certifi==2024.7.4
 + charset-normalizer==3.3.2
 + comm==0.2.2
...
```

And all of the packages (request, pyarrow, polars) will be installed into .venv within the project directory. We specify those packages in the pyproject.toml.

```toml
dependencies = ["pandas", "polars", "ipykernel", "pyarrow", "requests"]
```

Then when you start a Python interpreter, or open a notebook with the Python environment from `.venv` (you can force activate the shell with ` source .venv/bin/activate`) you an import all the packages.

**Review by jacksongoode — APPROVED** [review]
I've cleaned up the documentation since I believe what you might have experienced was because you didn't run uv from within the directory or perhaps didn't call the proper Python interpreter that has all the installed from the .venv folder.

Thanks for helping clarify the docs here!

**Comment by alwasega** [comment]
> I've cleaned up the documentation since I believe what you might have experienced was because you didn't run uv from within the directory or perhaps didn't call the proper Python interpreter that has all the installed from the .venv folder.
> 
> Thanks for helping clarify the docs here!

Thanks for the updates and for cleaning up the documentation. 
I am glad to have been of help as well :)

**Pull request merged**
